const key = 'pecuaria-em-dia-v1';
const seed = { expenses: [], purchases: [], sales: [] };
let data = JSON.parse(localStorage.getItem(key) || JSON.stringify(seed));
let currentView = 'dashboard';
const brl = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });
const money = n => brl.format(Number(n || 0));
const dateBR = d => new Intl.DateTimeFormat('pt-BR').format(new Date(`${d}T12:00:00`));
const today = new Date().toISOString().slice(0, 10);
const app = document.querySelector('#app');

function save() { localStorage.setItem(key, JSON.stringify(data)); }
function total(rows, field = 'value') { return rows.reduce((sum, x) => sum + Number(x[field] || 0), 0); }
function parseNum(v) { return Number(String(v || '0').replace(',', '.')) || 0; }
function schedule() {
  const start = new Date(2026, 6, 15); const principal = 500000, monthly = 6500, dilution = 1625;
  return Array.from({ length: 24 }, (_, i) => { const month = i + 1; const due = new Date(start); due.setMonth(start.getMonth() + i); const interest = month <= 3 ? 0 : monthly + (month <= 15 ? dilution : 0); const amortization = month === 24 ? principal : 0; return { month, due, phase: month <= 3 ? 'Carência' : month <= 15 ? 'Diluição' : 'Juros normais', interest, amortization, payment: interest + amortization }; });
}
function btnNew(type, label = 'Novo lançamento') { return `<button class="btn primary" data-new="${type}">+ ${label}</button>`; }
function dashboard() {
  const p = total(data.purchases), s = total(data.sales), e = total(data.expenses), next = schedule().find(x => x.due >= new Date());
  return `<div class="content"><div class="hero"><div><p class="eyebrow">OPERAÇÃO EM UM SÓ LUGAR</p><h2>Bom dia, Fabio.</h2><p>Acompanhe os números da fazenda e registre a movimentação de hoje.</p></div>${btnNew('purchase','Registrar compra')}</div><div class="cards"><div class="card"><div class="card-label">Compras de gado</div><div class="card-value">${money(p)}</div><div class="card-foot">${data.purchases.length} lote(s) registrado(s)</div></div><div class="card"><div class="card-label">Vendas de gado</div><div class="card-value green">${money(s)}</div><div class="card-foot">${data.sales.length} lote(s) registrado(s)</div></div><div class="card"><div class="card-label">Investimentos e gastos</div><div class="card-value red">${money(e)}</div><div class="card-foot">${data.expenses.length} lançamento(s)</div></div><div class="card"><div class="card-label">Resultado operacional</div><div class="card-value ${s-p-e >= 0 ? 'green' : 'red'}">${money(s-p-e)}</div><div class="card-foot">Vendas − compras − gastos</div></div></div><div class="grid-2"><div class="panel"><div class="panel-head"><div><h3>Próximos compromissos do capital de giro</h3><small>Empréstimo de R$ 500.000 a 1,3% ao mês</small></div><button class="btn secondary" data-view-link="capital">Ver cronograma</button></div><div class="timeline">${next ? `<div class="timeline-row"><div><strong>${dateBR(next.due.toISOString().slice(0,10))}</strong><br><small>Mês ${next.month}</small></div><div><strong>${next.phase}</strong><br><small>${next.phase === 'Diluição' ? 'Juro do mês + parcela da carência' : 'Pagamento previsto'}</small></div><div class="amount">${money(next.payment)}</div></div>` : '<p class="empty">Cronograma concluído.</p>'}</div></div><div class="panel"><div class="panel-head"><h3>Atalhos</h3></div><div class="timeline"><div class="timeline-row"><div>↓</div><div><strong>Compra de gado</strong><br><small>Registre um lote adquirido</small></div>${btnNew('purchase','Adicionar')}</div><div class="timeline-row"><div>↑</div><div><strong>Venda de gado</strong><br><small>Registre uma venda realizada</small></div>${btnNew('sale','Adicionar')}</div><div class="timeline-row"><div>▣</div><div><strong>Gasto ou investimento</strong><br><small>Frete, sanidade, alimentação e mais</small></div>${btnNew('expense','Adicionar')}</div></div></div></div></div>`;
}
function capital() { const rows = schedule(); return `<div class="content"><div class="section-title"><div><h2>Capital de giro</h2><p>R$ 500.000 · 24 meses · juros de 1,3% ao mês</p></div><span class="pill gold">Carência: 3 meses</span></div><div class="cards"><div class="card"><div class="card-label">Juro mensal base</div><div class="card-value">${money(6500)}</div></div><div class="card"><div class="card-label">Juros da carência</div><div class="card-value">${money(19500)}</div><div class="card-foot">diluídos em 12 meses</div></div><div class="card"><div class="card-label">Total de juros</div><div class="card-value">${money(156000)}</div></div><div class="card"><div class="card-label">Total previsto</div><div class="card-value">${money(656000)}</div><div class="card-foot">inclui quitação do principal</div></div></div><div class="panel"><div class="panel-head"><div><h3>Cronograma de pagamento</h3><small>O principal está previsto para quitação no mês 24.</small></div></div><div class="table-wrap"><table><thead><tr><th>Mês</th><th>Vencimento</th><th>Fase</th><th>Juros pagos</th><th>Amortização</th><th>Pagamento previsto</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.month}</td><td>${dateBR(r.due.toISOString().slice(0,10))}</td><td><span class="pill ${r.phase==='Diluição'?'gold':''}">${r.phase}</span></td><td>${money(r.interest)}</td><td>${money(r.amortization)}</td><td class="amount">${money(r.payment)}</td></tr>`).join('')}</tbody></table></div></div></div>`; }
function recordsView(kind) {
  const cfg = { gastos: { title:'Investimentos e gastos', desc:'Registre custos, despesas e investimentos da operação.', rows:data.expenses, type:'expense', cols:['Data','Tipo','Categoria','Descrição','Lote','Fornecedor / Beneficiário','Valor'], values:r=>[dateBR(r.date),r.type,r.category,r.description,r.lot,r.party,money(r.value)] }, compras: { title:'Compras de gado', desc:'Lotes adquiridos para a operação.', rows:data.purchases, type:'purchase', cols:['Lote','Data','Tipo de animais','Sexo','Quantidade','Frete','Valor pago','Vendedor'], values:r=>[r.lot,dateBR(r.date),r.animalType,r.sex,r.quantity,money(r.freight),money(r.value),r.party] }, vendas: { title:'Vendas de gado', desc:'Lotes comercializados pela operação.', rows:data.sales, type:'sale', cols:['Lote','Data','Tipo de animais','Sexo','Quantidade','Frete','Valor recebido','Comprador'], values:r=>[r.lot,dateBR(r.date),r.animalType,r.sex,r.quantity,money(r.freight),money(r.value),r.party] } }[kind];
 return `<div class="content"><div class="section-title"><div><h2>${cfg.title}</h2><p>${cfg.desc}</p></div><div class="sheet-actions"><select class="filter"><option>Todos os períodos</option><option>Este mês</option><option>Este ano</option></select>${btnNew(cfg.type)}</div></div><div class="summary-strip"><div>Total de lançamentos<strong>${cfg.rows.length}</strong></div><div>Valor acumulado<strong>${money(total(cfg.rows))}</strong></div><div>Atualização<strong>Agora</strong></div></div><div class="panel"><div class="table-wrap"><table><thead><tr>${cfg.cols.map(c=>`<th>${c}</th>`).join('')}<th></th></tr></thead><tbody>${cfg.rows.length ? cfg.rows.map((r,i)=>`<tr>${cfg.values(r).map(v=>`<td>${v || '—'}</td>`).join('')}<td><button class="btn danger" data-delete="${cfg.type}" data-index="${i}">Excluir</button></td></tr>`).join('') : `<tr><td class="empty" colspan="${cfg.cols.length+1}">Ainda não há lançamentos. Use o botão “Novo lançamento” para começar.</td></tr>`}</tbody></table></div></div></div>`;
}
function render() { document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView)); document.querySelector('#pageTitle').textContent = ({dashboard:'Visão geral',capital:'Capital de giro',gastos:'Investimentos e gastos',compras:'Compras de gado',vendas:'Vendas de gado'})[currentView]; app.innerHTML = currentView==='dashboard'?dashboard():currentView==='capital'?capital():recordsView(currentView); bindPage(); }
const field = (name,label,type='text',opts='',full=false) => `<label class="${full?'full':''}">${label}<${type==='select'?'select':'input'} name="${name}" ${type==='date'?'type="date"':type==='number'?'type="number" step="0.01" min="0"':''}>${opts}</${type==='select'?'select':'input'}></label>`;
function openForm(type) { const d=document.querySelector('#recordDialog'), f=document.querySelector('#formFields'); const isExpense=type==='expense', isSale=type==='sale'; document.querySelector('#modalTitle').textContent=isExpense?'Adicionar gasto ou investimento':isSale?'Registrar venda de gado':'Registrar compra de gado'; document.querySelector('#modalEyebrow').textContent=isExpense?'INVESTIMENTOS E GASTOS':isSale?'VENDA DE GADO':'COMPRA DE GADO'; f.innerHTML = isExpense ? field('date','Data','date')+field('type','Tipo','select','<option>Gasto</option><option>Investimento</option><option>Despesa</option>')+field('category','Categoria','select','<option>Frete</option><option>Alimentação</option><option>Sanidade</option><option>Mão de obra</option><option>Infraestrutura</option><option>Financeiro</option><option>Outro</option>')+field('lot','Lote')+field('party','Fornecedor / beneficiário')+field('value','Valor (R$)','number')+field('description','Descrição','text','',true) : field('lot','Identificação do lote')+field('date','Data','date')+field('animalType','Tipo de animais','select','<option>Bezerro</option><option>Garrote</option><option>Novilho</option><option>Vaca</option><option>Boi gordo</option><option>Outro</option>')+field('sex','Sexo','select','<option>Macho</option><option>Fêmea</option>')+field('quantity','Quantidade','number')+field('freight','Custo de frete (R$)','number')+field('value',isSale?'Valor recebido (R$)':'Valor pago (R$)','number')+field('party',isSale?'Comprador':'Vendedor')+field('city','Cidade')+field('state','Estado')+`<label class="full">Observações<textarea name="notes"></textarea></label>`; f.querySelector('[name=date]').value=today; d.dataset.type=type; d.showModal(); }
function bindPage(){ document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>openForm(b.dataset.new)); document.querySelectorAll('[data-view-link]').forEach(b=>b.onclick=()=>{currentView=b.dataset.viewLink;render()}); document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const map={expense:'expenses',purchase:'purchases',sale:'sales'};data[map[b.dataset.delete]].splice(Number(b.dataset.index),1);save();render()}); }
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;document.querySelector('#sidebar').classList.remove('open');render()});
document.querySelector('#menuBtn').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');
document.querySelector('#recordForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget), row=Object.fromEntries(fd.entries()), map={expense:'expenses',purchase:'purchases',sale:'sales'};['value','freight','quantity'].forEach(k=>row[k]=parseNum(row[k]));data[map[document.querySelector('#recordDialog').dataset.type]].unshift(row);save();document.querySelector('#recordDialog').close();render()});
render();
